"""Central configuration: event facts, hub structure, environment.

Every event fact (dates, venue, day themes, links) lives in this ONE file so
it can be corrected in one place. EVENT_FACTS_VERIFIED records what was
checked and where; anything still a placeholder says so.
"""
import datetime as _dt
import os
import secrets

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(BASE_DIR, ".env")


def _load_env():
    """Tiny .env loader (no python-dotenv dependency)."""
    data = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip()
    return data


def _ensure_env():
    """Create .env with a generated SECRET_KEY on first run."""
    env = _load_env()
    if "SECRET_KEY" not in env:
        env["SECRET_KEY"] = secrets.token_hex(32)
        with open(ENV_PATH, "w", encoding="utf-8") as f:
            f.write("# Generated by devcon-security-hub. Keep private.\n")
            for k, v in env.items():
                f.write("%s=%s\n" % (k, v))
        try:
            os.chmod(ENV_PATH, 0o600)
        except OSError:
            pass
    return env


ENV = _ensure_env()
# Real environment variables win over .env (tests and systemd use this).
for _k in ("HUB_DB_PATH", "PORT", "SECRET_KEY"):
    if os.environ.get(_k):
        ENV[_k] = os.environ[_k]

SECRET_KEY = ENV["SECRET_KEY"]
DB_PATH = ENV.get("HUB_DB_PATH") or os.path.join(BASE_DIR, "hub.db")
PORT = int(ENV.get("PORT", "4590"))
TRUST_PROXY = ENV.get("TRUST_PROXY", "").strip() in ("1", "true", "yes")
SITE_URL = ENV.get("SITE_URL", "").strip().rstrip("/")
if SITE_URL and "://" not in SITE_URL:
    SITE_URL = "https://" + SITE_URL
COOKIE_SECURE = (ENV.get("COOKIE_SECURE", "").strip() in ("1", "true", "yes")
                 or SITE_URL.startswith("https"))
LOGIN_ATTEMPTS_PER_MINUTE_PER_IP = 5

# ------------------------------------------------------------- event facts
# VERIFIED 2026-10-07 against the devcon.org homepage, which reads
# "Mumbai India · 3–6 November 2026" and "Devcon will take place at the
# Jio World Centre". Re-check before launch; Devcon may still publish changes.
EVENT_FACTS_VERIFIED = True
EVENT_FACTS_SOURCE = "devcon.org homepage, checked 2026-10-07"

EVENT_NAME = "Devcon 8 India"
HUB_NAME = "Security Hub"
EVENT_CITY = "Mumbai, India"
EVENT_VENUE = "Jio World Centre"
# PLACEHOLDER: Devcon has not assigned the hub's floor or room yet.
HUB_LOCATION = ENV.get("HUB_LOCATION", "Floor and room to be announced")
TIMEZONE_NAME = "Asia/Kolkata"
TZ = _dt.timezone(_dt.timedelta(hours=5, minutes=30), "IST")  # no DST in India

MISSION = ("A four-day working space where Ethereum security researchers, "
           "builders, responders and newcomers meet, learn and coordinate.")

# Day number -> (date, theme, one-line description from the forum proposal)
DAYS = {
    1: (_dt.date(2026, 11, 3), "Meet the Security Community",
        "Welcome, contributor introductions, open discussions and networking."),
    2: (_dt.date(2026, 11, 4), "Security for Builders",
        "Practical workshops, builder questions, tool demos and security clinics."),
    3: (_dt.date(2026, 11, 5), "Incident Response and Coordination",
        "Incident-response exercises, investigations, lessons learned and coordination."),
    4: (_dt.date(2026, 11, 6), "Getting Involved in Ethereum Security",
        "Contributor pathways, open-source opportunities, community-led sessions and closing conversations."),
}

HUB_OPEN_MIN = 9 * 60     # 09:00 IST
HUB_CLOSE_MIN = 18 * 60   # 18:00 IST
# Default host shifts created for every day on first boot (minutes since midnight).
DEFAULT_SHIFTS = [(9 * 60, 12 * 60), (12 * 60, 15 * 60), (15 * 60, 18 * 60)]
MIN_GAP_MINUTES = 5       # gaps shorter than this warn (override allowed)

HANDOVER_NOTE = ENV.get(
    "HANDOVER_NOTE",
    "Hosts arrive 15 to 30 minutes before their shift for the handover.")

SESSION_TYPES = ["talk", "workshop", "fishbowl", "roundtable", "game",
                 "office hours"]

# ---------------------------------------------------------------- links
PROPOSAL_URL = "https://forum.devcon.org/t/devcon-8-india-community-hub-security-hub/8786"
HUBS_ANNOUNCEMENT_URL = "https://forum.devcon.org/t/announcing-the-devcon-8-india-community-hubs/9191"
# PLACEHOLDER: the Telegram group does not exist yet. Set TELEGRAM_URL in .env.
TELEGRAM_URL = ENV.get("TELEGRAM_URL", "").strip()

ORGANIZERS = [
    ("Anamarija", "https://x.com/anamarie_com"),
    ("Griff Green", "https://x.com/griffgreen"),
    ("Lanski", "https://x.com/Pol_Lanski"),
    ("Jake", "https://x.com/GivJake"),
    ("Cotabe", "https://x.com/Cotabe_M"),
]
ORGANIZED_BY = ("TheDAO Security Fund", "https://thedao.fund/")
DISCLAIMER = ("Community-run hub. Not an official Devcon or Ethereum "
              "Foundation page.")
